public enum CollectionType
{
    // Fish
    // 1 star

    RedEyedCarp,
    Anchovy,
    SeaCucumber,
    Tilapia,
    NeonFish,
    RedArowana,
    BlueSunfish,
    Pufferfish,
    SeaSlug,
    FinnyScad,
    RedEaredTurtle,
    SeaBass,
    SweetShrimp,
    Salmon,
    RainbowEel,
    Minnows,
    SmallCrab,
    LittleStarfish,
    CrucianCarp,
    Flatworms,
    RedBelliedTurtle,
    Tuna,
    SweetFish,
    BlackSeaBass,
    FieldFish,
    HermitCrab,
    SmallJellyFish,
    GiantGourami,
    Flounder,
    CatFish,
    // 2 star
    PlatinumGuppies,
    TuxedoGuppies,
    Scallops,
    DungnessCrab,
    RainbowFish,
    SeaUrchin,
    NorthernPike,
    CrownGuppies,
    PandaGuppies,
    DwarfOctopus,
    FreshwaterLobster,
    GrassGuppies,
    SnakeskinGuppy,
    HornSnail,
    LionFish,
    GlassGuppy,
    WhiteGuppy,
    BlueTailFish,
    ChumSalmon,
    MosaicGuppies,
    GlassesGoldFish,
    SuckermouthCatFish,
    SwordtailGuppy,
    Oyster,
    KingSalmon,
    Remora,
    NautilusPompilius,
    RibbonGuppies,
    RedGarraFish,
    FireflySquid,
    // 3 star
    MantisShrimp,
    HorseshoeCrab,
    LargemouthBass,
    SmallTigerFish,
    SilverFish,
    DoctorFish,
    BlueberryGoldFish,
    GrassCarp,
    ClownFish,
    FlapjackOctopus,
    SpinyLobster,
    ButterflyMask,
    SeaBream,
    SwimmingCrab,
    LenokPointedBeakSalmon,
    AmethystQuartzPerch,
    ThreeEyedHalibut,
    TigerFish,
    SilverSnapper,
    ChineseHairyCrab,
    OysterNgoc,
    SpottedClownFish,
    PencilSeaUrchin,
    BlueSeaStar,
    GreenSeaTurtle,
    // 4 star
    FangedTuna,
    RayFish,
    AngelFishEmperor,
    RocketFish,
    VampireInk,
    LampFish,
    NorthernSnakeheadFish,
    MorayEel,
    BettaFish,
    MoonJellyFish,
    MahiMahiFish,
    PaddleFish,
    GreenlandShark,
    ArapaimaFish,
    StoneChrysanthemumFish,
    RedSeaStar,
    GiantTilapia,
    BlueRingedOctopus,
    OneSpottedGrouper,
    KingCrab,
    NasoTangFish,
    KoiFish,
    Lobster,
    GiantPufferFish,
    OceanSunfish,
    // 5 star

    PandaButterflyFish,
    FishAchillesTang,
    SickleFish,
    SapphireFish,
    GoldenSalmon,
    HumpheadWrasse,
    SiberianTaimenFish,
    SnappingTurtle,
    TorentialPiranha,
    HammerheadShark,
    GoldenBassletFish,
    ArowanaFish,
    MantaRayFish,
    BastardSturgeon,
    Manatee,
    BluefinTuna,
    GiantClam,
    DoradoFish,
    HumpbackWhale,
    NeptuneGrouper,
    DumboOctopus,
    GiantOctopus,
    FlagFish,
    LoggerheadSeaTurtle,
    SeaBeetle,
    WhiteSturgeon,
    TalkingCatfish,
    Redtilapia,
    SpoonSturgeon,
    BlackKillifish,
    SpiderCrab,
    PeppermintFish,
    PearlscaleTilapia,
    Sawfish,
    GreatWhiteShark,
    BlueLobster,
    GobyFish,
    PacificShark,
    ExoticShrimp,
    PlacodermFish,

    // Treasure
    // 1 star

    Shoe,
    Katana,
    Ax,
    PetBowl,
    Emptycans,
    CeramicVase,
    WalkieTalkie,
    Doll,
    WaterBottle,
    CaptainHat,
    DriftingBottle,
    TobaccoPipe,
    Clinch,
    ImitationWoodenLegs,
    Denture,
    PocketWatch,
    HurricaneLamp,
    SteelBucket,
    Whisky,
    Camera,
    ShortKnife,
    Periscope,
    Micro,
    Mask,
    Helm,
    BaseballBat,
    Hourglass,
    Safe,
    WoodenBox,
    Anchor,

    // 2 star

    BronzeBell,
    Timepiece,
    Torpedo,
    MagicHat,
    MusicBox,
    ElectricGuitar,
    CrystalBall,
    Mailbox,
    FireHydrant,
    Drone,
    BloodCage,
    DecorativeSkull,
    WoodenSoldier,
    PortraitPhoto,
    RadarBroken,
    Robot,
    DivingBell,
    ScrapSubmarine,
    Motorbike,
    Aircraft,

    // 3 star

    Crown,
    MagicLamp,
    ArmorePoliceCar,
    Microscope,
    GoldenStatue,
    Globe,
    PhonographRecordPlayer,
    ShipInBottle,
    SextantGlass,
    MafiaHat,

    // Chest

    Chest,
    CeramicChest,
    WeaponChest,
    GoldenChest,
    GemChest,
    JewelryChest,

    // Diver

    Adam,
    March,
    Peter,
    Tary,
    Zeus,
    Aduin,
    Hanzo,
    Henry,
    Sanji
}